# import turtle
# turtle.Screen().bgcolor("red")
# sc=turtle.Screen()
# sc.setup(500,500)
# turtle.title("turtle window")
# board=turtle.Turtle()
# board.fillcolor("Yellow")
# board.begin_fill()
# board.forward(100)
# board.left(90)
# board.forward(100)
# board.left(90)
# board.forward(100)
# board.left(90)
# board.forward(100)
# board.end_fill()
# turtle.done()
        #activity 2
import turtle
turtle.Screen().bgcolor("red")
sc=turtle.Screen()
sc.setup(500,500)
turtle.title("turtle window")
board=turtle.Turtle()
board.fillcolor("Yellow")
board.begin_fill()
board.forward(100)
board.left(120)
board.forward(100)
board.left(120)
board.forward(100)
board.end_fill()
board.penup()
board.right(150)
board.forward(50)
board.pendown()
board.fillcolor("Yellow")
board.begin_fill()
board.right(90)
board.forward(100)
board.right(120)
board.forward(100)
board.right(120)
board.forward(100)
board.end_fill()

turtle.done()